### ISSUE TITLE
texlive2018 编译出错

### ISSUE THREAD

**Issue by procuteboy** [NewFuture/NKThesis#1]
texlive2018 编译出错
``
Undefined control sequence.\NKT 
``
之前好像没这个问题，可能问题出在这个NKT宏包吧。

**Comment by dudu19939** [comment]
同样问题，请问如何解决？

**Comment by NewFuture** [comment]
是运行的 [build.cmd](https://github.com/NewFuture/NKThesis/blob/master/build.cmd) 吗？

**Comment by dudu19939** [comment]
在VScode中运行的。

**Comment by dudu19939** [comment]
刚刚试了一下在终端运行build.cmd，仍然有这个bug。
ps：我的环境是macOS。

**Comment by procuteboy** [comment]
windows 10 报错
可能跟texlive2018升级有关，我试试能不能修好

**Comment by NewFuture** [comment]
还有问题可以和 @jinjilr 交流一下 😄

**Comment by procuteboy** [comment]
````
\def\NKT@tp@item#1#2{%
  #1%
  \hskip 0.5em%
  \underline{\hbox to 50mm{\hfil#2\hfil}}}
  
\def\NKT@tp@itemv#1#2{%
  \NKT@tp@item{#1}{\NKT@keyvalue{#2}}}
````
NKthesis.cfg 调到最前 
把main.tex 中教授中间的$\sim$去掉。

**Comment by NewFuture** [comment]
@procuteboy 可以提个PR

**Comment by loveklmn** [comment]
@dudu19939  请问mac平台成功了吗..
