### ISSUE TITLE
建议修改说明文档中过时的说明

### ISSUE THREAD

**Issue by syvshc** [NewFuture/NKThesis#12]
建议修改过时的说明. 比如

1. 建议使用 `.eps` 格式图片, 现在 latex 对于各种通用的图片格式支持良好, 而不像 `.eps` 需要调用外部程序, 且用其他软件导出 `.eps` 格式文件的操作可能更为复杂. 
2. 在论坛 bbs.ctex.org (现已关闭) 中搜索

**Comment by NewFuture** [comment]
欢迎提个pull request 更新一下
