### ISSUE TITLE
字体缺失

### ISSUE THREAD

**Issue by zsh2020** [NewFuture/NKThesis#13]
Font shape `TU/ppl/m/n' undefined(Font) using `TU/lmr/m/n' instead

**Comment by NewFuture** [comment]
可以帮忙更新一下 😂

**Comment by zsh2020** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        大佬，我不会呀，能教一下怎么改模板傻的吗，今年学校又更新了模板。
        
    
        
            
        
    
    
        
        

        
    

    在2020年12月10日 13:05，New Future<notifications@github.com> 写道： 




可以帮忙更新一下 😂

**Comment by zsh2020** [comment]
好的

**Comment by NewFuture** [comment]
字体配置 https://github.com/NewFuture/NKThesis/blob/master/NKTfonts.cfg
模板样式 https://github.com/NewFuture/NKThesis/blob/master/NKThesis.sty

**Comment by zsh2020** [comment]
> 
> 
> 字体配置 https://github.com/NewFuture/NKThesis/blob/master/NKTfonts.cfg
> 模板样式 https://github.com/NewFuture/NKThesis/blob/master/NKThesis.sty

我研究一下

**Comment by zsh2020** [comment]
大佬 方便联系吗？请教一些问题，不知道怎么去改这些东西呢

**Comment by NewFuture** [comment]
可以发微信到邮件github@newfuture.cc
