### ISSUE TITLE
如何引用(cite)参考文献，比如使正文中出现Wang (2020)，张三和李四 (2020) 这种类型的引用格式？

### ISSUE THREAD

**Issue by MarkRonnie** [NewFuture/NKThesis#14]
正文引用文献时如何设置成姓名+年份的形式，而不是[1][2]这种数字编号类型的。谢谢解答

**Comment by NewFuture** [comment]
看看这个 https://www.overleaf.com/learn/latex/Biblatex_citation_styles

**Comment by hushidong** [comment]
biblatex样式换成gb7714-2015ay即可

**Comment by MarkRonnie** [comment]
> biblatex样式换成gb7714-2015ay即可

**Comment by JinChengneng** [comment]
> biblatex样式换成gb7714-2015ay即可

在使用gb7714-2015ay后，文献中作者数量超过两人的情况下，引用格式为“XXX et al. (20XX)”。但在中文论文中，正确的引用格式应为“XXX 等人（20XX）”或“（XXX 等人，20XX）”，这取决于使用的是\citet{}（用于文本引用）还是\citep{}（用于括号引用）。请问应该怎么修改？

**Comment by NewFuture** [comment]
> > biblatex样式换成gb7714-2015ay即可
> 
> 在使用gb7714-2015ay后，文献中作者数量超过两人的情况下，引用格式为“XXX et al. (20XX)”。但在中文论文中，正确的引用格式应为“XXX 等人（20XX）”或“（XXX 等人，20XX）”，这取决于使用的是\citet{}（用于文本引用）还是\citep{}（用于括号引用）。请问应该怎么修改？

猜测，在bib中加上语言有用吗？
```sh
userf = {zh},
```
