### ISSUE TITLE
pdf 书签是错误

### ISSUE THREAD

**Issue by liu-xb** [NewFuture/NKThesis#15]
pdf书签中是“第1零章”，“第2零章”这种形式，而且报出Package hyperref Warning: Token not allowed in a PDF string (Unicode): (hyperref) removing `\CJK@q' on input line 99. 标题题目都是中文汉字和英文没有特殊符号的。文件编码方式为 utf8.

**Comment by Czw007** [comment]
请问已经解决了吗

**Comment by Czw007** [comment]
<img width="288" alt="image" src="https://github.com/NewFuture/NKThesis/assets/54148853/7e3f4301-4e22-4f89-b52a-c731a216a40d">
通过这个地方选2020版本解决了

**Comment by liu-xb** [comment]
哇好嘞，非常感谢~
