### ISSUE TITLE
texlive2021编译有大量报错，请求修复。

### ISSUE THREAD

**Issue by yuhuangniu** [NewFuture/NKThesis#16]
另外学校的论文写作规范也更新了：[南开大学研究生学位论文写作规范（修订版）20200311](https://graduate.nankai.edu.cn/2017/0222/c3325a56863/page.htm)。
请求跟进。
感谢。

**Comment by NewFuture** [comment]
欢迎PR

**Comment by slzhangsd** [comment]
可否提供编译通过的overleaf链接？

**Comment by yuhuangniu** [comment]
> 可否提供编译通过的overleaf链接？

在overleaf 里把texlive版本调成texlive2018就可以编译通过了。

**Comment by JYBWOB** [comment]
> > 可否提供编译通过的overleaf链接？
> 
> 在overleaf 里把texlive版本调成texlive2018就可以编译通过了。

overleaf里设置编译器xelatex，textlive2018还是不能成功编译，提示编译时间超时了
![image](https://github.com/NewFuture/NKThesis/assets/44292122/71b14fc0-6e28-4dde-8c6e-c07eed167021)

**Comment by Liuyulun** [comment]
> 可否提供编译通过的overleaf链接？

友友现在解决了吗？我也需要

**Comment by yuhuangniu** [comment]
> > 可否提供编译通过的overleaf链接？
> 
> 友友现在解决了吗？我也需要

学校内网上提供了新的LaTex模板，这个版本编译非常稳定，几乎没有bug。链接是：http://222.30.43.145/newlist.action?encid=58

**Comment by Liuyulun** [comment]
谢谢友友，刚还准备上bbs上问一下。BTW，现在bbs注册需要缴费了？我记得之前是不用的，而且感觉也不是之前的界面了。
















在 2024-04-29 20:19:40，"Yuhuang" ***@***.***> 写道：

可否提供编译通过的overleaf链接？

友友现在解决了吗？我也需要

学校内网上提供了新的LaTex模板，这个版本编译非常稳定，几乎没有bug。链接是：http://222.30.43.145/newlist.action?encid=58

**Comment by yuhuangniu** [comment]
> 谢谢友友，刚还准备上bbs上问一下。BTW，现在bbs注册需要缴费了？我记得之前是不用的，而且感觉也不是之前的界面了。 在 2024-04-29 20:19:40，"Yuhuang" ***@***.***> 写道： 可否提供编译通过的overleaf链接？ 友友现在解决了吗？我也需要 学校内网上提供了新的LaTex模板，这个版本编译非常稳定，几乎没有bug。链接是：http://222.30.43.145/newlist.action?encid=58 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我的账号是几年前注册的，当时是免费的，现在注册账号是什么情况不甚了了。

**Comment by Liuyulun** [comment]
我的账号忘了

谢谢友友













在 2024-04-29 20:31:22，"Yuhuang" ***@***.***> 写道：

谢谢友友，刚还准备上bbs上问一下。BTW，现在bbs注册需要缴费了？我记得之前是不用的，而且感觉也不是之前的界面了。 在 2024-04-29 20:19:40，"Yuhuang" @.> 写道： 可否提供编译通过的overleaf链接？ 友友现在解决了吗？我也需要 学校内网上提供了新的LaTex模板，这个版本编译非常稳定，几乎没有bug。链接是：http://222.30.43.145/newlist.action?encid=58 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

我的账号是几年前注册的，当时是免费的，现在注册账号是什么情况不甚了了。

**Comment by NewFuture** [comment]
> 学校内网上提供了新的LaTex模板，这个版本编译非常稳定，几乎没有bug。链接是：http://222.30.43.145/newlist.action?encid=58

我访问不了，连接可靠不，谁在维护？我打算放到readme里

**Comment by NewFuture** [comment]
已更新至2024 #36
