### ISSUE TITLE
参考文献格式编译出现问题

### ISSUE THREAD

**Issue by wittyblue** [NewFuture/NKThesis#19]
您好 我在使用texstudio+texlive2021进行编译时 参考文献中文献标题与文献标识（比如[M]）之间多出来一个英文句号（比如 文献标题.[M]）,请问我该怎么解决

**Comment by NewFuture** [comment]
已经很多年不写论文了，有兴趣的同学可以来帮忙维护/答疑 😅

**Comment by hushidong** [comment]
给个例子出来，包括bib信息的，这样方便解决，否则是没法复现问题的。

**Comment by hushidong** [comment]
解决就好。

**Comment by myhui0524** [comment]
> wittyblue



> 您好 我在使用texstudio+texlive2021进行编译时 参考文献中文献标题与文献标识（比如[M]）之间多出来一个英文句号（比如 文献标题.[M]）,请问我该怎么解决

请问您解决了吗，我今天也遇到了这个问题

**Comment by hushidong** [comment]
替换库里面的bbx和cbx。或者删掉库里的bbx/CBX后，更新biblatex-gb7714-2015

**Comment by myhui0524** [comment]
> 替换库里面的bbx和cbx。或者删掉库里的bbx/CBX后，更新biblatex-gb7714-2015
感谢感谢！已经解决啦！

**Comment by NewFuture** [comment]
如果是这个库需要更新 欢迎PR 😹

**Comment by wittyblue** [comment]
您好，很高兴您能关注到此问题。
该问题我已解决。经仔细研究发现，模板中提供的gb7714-2015相关文件定义的格式与gb7714-2015官方文档中所描述的格式存在偏差，该偏差表现为文献标题与文献类型标识之间存在多余的英文句号（如附录图中红线标记所示）。将模板中提供的gb7714-2015.bbx与gb7714-2015.cbx两个文件替换为https://github.com/hushidong/biblatex-gb7714-2015中对应的两个文件即可解决该问题。














在 2022-03-13 ***@***.***" ***@***.***> 写道：

给个例子出来，包括bib信息的，这样方便解决，否则是没法复现问题的。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NewFuture** [comment]
@hushidong  @wittyblue 有空可以提个Pull Request 帮忙更正一下
