### ISSUE TITLE
请教如何在每一章之后添加本章的“参考文章”，以及如何更改默认编译方式？

### ISSUE THREAD

**Issue by jinjilr** [NewFuture/NKThesis#2]
你好，请教一下，
1、如何在每一章之后添加本章的“参考文章”？
如果在每章之后添加\begin{thebibliography}...\bibitem{}...\end{thebibliography}，则该参考文献部分的页眉是“参考文献”，而不是每章标题。

2、目前默认的编译方式是XeLaTeX + biber，不过这个编译方式明显比pdflatex要慢很多（texlive2016，win10）。
在main.tex最上面部分更改的话会报错。
请问如何更改编译方式为pdflatex + bibtex？

谢谢！

**Comment by NewFuture** [comment]
1.  这个是可以实现的，你可以搜一下
2.  有些插件pdflatex是不支持的，然后参考文献的格式bibtex应该编译不了，当时都尝试过 😂 你可以再尝试一下

**Comment by jinjilr** [comment]
> 1. 这个是可以实现的，你可以搜一下
> 2. 有些插件pdflatex是不支持的，然后参考文献的格式bibtex应该编译不了，当时都尝试过 😂 你可以再尝试一下

谢谢，解决了xelatex编译慢的问题 😂

**Comment by jinjilr** [comment]
@NewFuture 
谢谢，解决了xelatex编译慢的问题😂

**Comment by NewFuture** [comment]
👍 @jinjilr 嗯，可以缓存
