### ISSUE TITLE
只有专业硕士学位选项不会被打勾

### ISSUE THREAD

**Issue by Guicai996** [NewFuture/NKThesis#22]
main.tex #L82的四个选项，只有专业学位硕士不会自动打勾，是不是字符串匹配有问题。

**Comment by NewFuture** [comment]
看起来像这段代码处理的
https://github.com/NewFuture/NKThesis/blob/744226c223987d2e23b8db728576ba9b10c197f4/NKThesis.cfg#L213-L221

**Comment by zlgNow** [comment]
您好，请问您最后解决了吗？

**Comment by NewFuture** [comment]
看了一下代码，这两个地方定义的不一样，

https://github.com/NewFuture/NKThesis/blob/058c1276b1a7d798c1acf5e451a882e56415710b/main.tex#L74

https://github.com/NewFuture/NKThesis/blob/058c1276b1a7d798c1acf5e451a882e56415710b/NKThesis.cfg#L243

https://github.com/NewFuture/NKThesis/blob/058c1276b1a7d798c1acf5e451a882e56415710b/NKThesis.sty#L630

把这三个地方改成一样的试试

**Comment by zlgNow** [comment]
谢谢！已解决啦

**Comment by NewFuture** [comment]
可以帮忙提个PR fix一下 😄

**Comment by zlgNow** [comment]
好嘞，莫得问题
