### ISSUE TITLE
英文文献作者名全大写，请问有什么方法可以改成首字母大写

### ISSUE THREAD

**Issue by theorynice** [NewFuture/NKThesis#28]
![image](https://github.com/NewFuture/NKThesis/assets/39797845/e05c8326-ba4b-4aea-8cdc-83a485dc9e88)

**Comment by hushidong** [comment]
https://github.com/hushidong/biblatex-gb7714-2015/blob/master/README.md?plain=1#L731-L740

**Comment by theorynice** [comment]
> https://github.com/hushidong/biblatex-gb7714-2015/blob/master/README.md?plain=1#L731-L740

谢谢，大家请在NKThesis.sty里按以上链接方法修改

**Comment by NewFuture** [comment]
如果是规范要求的格式，可以提个PR在模板里更新一下
