### ISSUE TITLE
请问如何更改公式格式为Times New Roman？

### ISSUE THREAD

**Issue by jinjilr** [NewFuture/NKThesis#3]
你好，
请问如何更改公式格式为Times New Roman？
目前并不是，如下
![image](https://user-images.githubusercontent.com/17511646/52845237-8fff0180-3141-11e9-9396-66144ad11dc5.png)
正确的应该是
![image](https://user-images.githubusercontent.com/17511646/52845308-c046a000-3141-11e9-8d1a-0eaadac6be56.png)

请问该如何在NKTfonts.cfg中进行更改？
谢谢！

**Comment by NewFuture** [comment]
用times包试一下

http://www.latexstudio.net/archives/7697.html

**Comment by jinjilr** [comment]
@NewFuture 
不行。平时写小论文用\usepackage{mathptmx}是可以的。

**Comment by NewFuture** [comment]
xelatex的字体配置在这里

https://github.com/NewFuture/NKThesis/blob/c754dda016be23c4d480112f44923f6139222582/NKTfonts.cfg#L9-L11

**Comment by jinjilr** [comment]
@NewFuture 
还有两个问题，
1、NKThesis.sty中，figure caption定义的是zihaowu，table caption定义的也是zihaowu。
但实际运行效果table caption是zihaowu，figure caption字体明显要大，肯定不是zihaowu，好像是zihaosi。
2、参考文献字号如何设置？
谢谢！

**Comment by NewFuture** [comment]
这个可能用的不是一个标签

**Comment by NewFuture** [comment]
通用的格式修改可以提个PR 😄

**Comment by jinjilr** [comment]
@NewFuture 
1、caption的问题解决了，应该是“标签”的原因。
figure的caption要用\figurecaption{}，不能直接用\caption{}。
2、参考文献仍然不知如何设置。
另外，不会PR(笑哭，表情都不会加)

**Comment by NewFuture** [comment]
参考文献可以再开一个issue

**Comment by Brice-fan** [comment]
> > 你好， 请问如何更改公式格式为Times New Roman？ 目前并不是，如下 ![image](https://user-images.githubusercontent.com/17511646/52845237-8fff0180-3141-11e9-9396-66144ad11dc5.png) 正确的应该是 ![image](https://user-images.githubusercontent.com/17511646/52845308-c046a000-3141-11e9-8d1a-0eaadac6be56.png)
> > 请问该如何在NKTfonts.cfg中进行更改？ 谢谢！
> 
> 数学字体的问题应该是这里调用了 `mathpazo` 包导致的。 https://github.com/NewFuture/NKThesis/blob/744226c223987d2e23b8db728576ba9b10c197f4/NKThesis.sty#L792K

感觉和times new roman还是有点偏差。比如加总符号和求和符号
<img width="389" alt="image" src="https://user-images.githubusercontent.com/62749876/224650698-023bea46-6334-41b7-a1d5-da3db7736d12.png">
正确的
<img width="385" alt="image" src="https://user-images.githubusercontent.com/62749876/224651471-14ffcb1f-b290-4e47-8481-fbe53338ebdc.png">

**Comment by TCLiuu** [comment]
> 感觉和times new roman还是有点偏差。比如加总符号和求和符号 <img alt="image" width="389" src="https://user-images.githubusercontent.com/62749876/224650698-023bea46-6334-41b7-a1d5-da3db7736d12.png"> 正确的 <img alt="image" width="385" src="https://user-images.githubusercontent.com/62749876/224651471-14ffcb1f-b290-4e47-8481-fbe53338ebdc.png">

可参考下面这个回答
https://www.zhihu.com/question/391007830/answer/1184553340
