### ISSUE TITLE
现在的目录包含了摘要和英文摘要，怎么去除呢？

### ISSUE THREAD

**Issue by velonica0** [NewFuture/NKThesis#31]

**Comment by NewFuture** [comment]
可根据提示，注释掉 11行 和 22 行。
https://github.com/NewFuture/NKThesis/blob/602dd5942ac20ea7abce2cbc40e06d4c2e678c40/NKThesis.cfg#L6-L26


PS: 当年写论文的时候是推荐把摘要列在目录上的
