### ISSUE TITLE
参考文献格式不对

### ISSUE THREAD

**Issue by IdeaMeshDyx** [NewFuture/NKThesis#32]
参考文献中存在 `.[C].[S.L.]`,去除需要添加新的配置文件取代原本的`gb7714-2015.bbx)` 和 `gb7714-2015.cbx`, 具体可用仓库位置：
https://github.com/hushidong/biblatex-gb7714-2015

**Comment by NewFuture** [comment]
可以帮忙更新一下😂

**Comment by NewFuture** [comment]
fixed by #23
