### ISSUE TITLE
请问有overleaf环境下可使用的博士论文模板吗？

### ISSUE THREAD

**Issue by Liuyulun** [NewFuture/NKThesis#33]
下载.zip文件导入后，mac系统编译失败，提示很多报错。
![WechatIMG992](https://github.com/NewFuture/NKThesis/assets/61680740/7d88c3e0-4ed3-4148-a470-c8ddeaee0a92)

**Comment by NewFuture** [comment]
> > [#8 (comment)](https://github.com/NewFuture/NKThesis/issues/8#issuecomment-1017274109)
> > 这个好使吗？ https://cn.overleaf.com/project/61e9170460e1190ebe60b09d
> 
> 提示我没有使用权限。 ![WechatIMG994](https://private-user-images.githubusercontent.com/61680740/326437045-41b9423e-9b6e-4552-83ca-f9a8eb05e093.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTQzNTQsIm5iZiI6MTcxNDM5NDA1NCwicGF0aCI6Ii82MTY4MDc0MC8zMjY0MzcwNDUtNDFiOTQyM2UtOWI2ZS00NTUyLTgzY2EtZjlhOGViMDVlMDkzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEyMzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODY1ZDc2ZDJlMDBmOGYyNGMzNzk1ZGYxNzM3M2NlZTA5M2QyNWZmODUxOTFhMDM2NjcwYmJhNTA3ZTY4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2MhLKfArjBxiKX5D9MBMPHPTadoSHgX4t-OjFUz6nEw)

哦，不好意思连接错了 https://cn.overleaf.com/read/hvcpznzvwncy

**Comment by Liuyulun** [comment]
> [#8 (comment)](https://github.com/NewFuture/NKThesis/issues/8#issuecomment-1017274109)
> 
> 这个好使吗？ https://cn.overleaf.com/read/hvcpznzvwncy

可以的，谢谢友友！祝您拥有美好生活：）

**Comment by NewFuture** [comment]
> 发现我不能编译，也不能下载到本地，请问怎么解决啊？

我试了一下，可以

![image](https://github.com/NewFuture/NKThesis/assets/6290356/b9a0bb90-7cba-4807-8963-1031c86d27c3)

**Comment by Liuyulun** [comment]
> > 发现我不能编译，也不能下载到本地，请问怎么解决啊？
> 
> 我试了一下，可以
> 
> ![image](https://private-user-images.githubusercontent.com/6290356/326443123-b9a0bb90-7cba-4807-8963-1031c86d27c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTYxNzgsIm5iZiI6MTcxNDM5NTg3OCwicGF0aCI6Ii82MjkwMzU2LzMyNjQ0MzEyMy1iOWEwYmI5MC03Y2JhLTQ4MDctODk2My0xMDMxYzg2ZDI3YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTMwNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVkMzEyZWNhZjIxZmQ2MTMwMDJhNjRiYjU3ZjhkOTE1NjBlN2Q2OTMwMmU2ZjcxN2M4MzA0MmY0ZGI3YjkyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gSdvG3hXnWfpKia7D7bsNLrcE1ArdEtyeWoh2WDnr10)

友友能再分享一次吗？我猜想可能是我把您第一分享的模板删除了，因为您可能是免费版的，只能用一个合作者，我再次打开的话就不能编辑了。

**Comment by Liuyulun** [comment]
> > 发现我不能编译，也不能下载到本地，请问怎么解决啊？
> 
> 我试了一下，可以
> 
> ![image](https://private-user-images.githubusercontent.com/6290356/326443123-b9a0bb90-7cba-4807-8963-1031c86d27c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTY1NjksIm5iZiI6MTcxNDM5NjI2OSwicGF0aCI6Ii82MjkwMzU2LzMyNjQ0MzEyMy1iOWEwYmI5MC03Y2JhLTQ4MDctODk2My0xMDMxYzg2ZDI3YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTMxMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNjZDQ1ODUzNmUzOTYwNWU2NDAzOWFjZTZmMjM4NGZiZWE4NDdhMjVlNmRhZjNiMDYxYWUzN2QwMDQ4OTFiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.47Hg8fVNQWpU-TUSWHcm0lAkzgeCPF_J5JEf0KHbZRk)

我复制新建了一个项目，可以了，谢谢友友
