### ISSUE TITLE
请问如何改封面作者信息等字体的大小

### ISSUE THREAD

**Issue by theorynice** [NewFuture/NKThesis#39]

**Comment by theorynice** [comment]
这个修.cfg里的对应字号就可以

**Comment by NewFuture** [comment]
这个标准改了吗？

**Comment by theorynice** [comment]
大家都用五号字，但标准里是小四，应该不用改了



---Original---
From: "New ***@***.***&gt;
Sent at: 2024年5月24日(Fri) Noon11:39
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [NewFuture/NKThesis] 请问如何改封面作者信息等字体的大小 (Issue #39)




 
这个标准改了吗？

**Comment by NewFuture** [comment]
是这个吗？上面是小四
![image](https://github.com/NewFuture/NKThesis/assets/6290356/721534d0-b974-447d-b881-ec31abb7de9e)

**Comment by theorynice** [comment]
不好意思啊，那是我这边规范有误啦
