### ISSUE TITLE
请问如何更改参考文献、致谢、个人简历的字体大小？

### ISSUE THREAD

**Issue by jinjilr** [NewFuture/NKThesis#4]
参考文献、致谢、个人简历目前是小四，请问如何改成五号？其他章节保持不变。
小四的参考文献实在太占页数。
谢谢！

**Comment by NewFuture** [comment]
试试 https://www.jianshu.com/p/ad400d7fe885

**Comment by jinjilr** [comment]
@NewFuture 
我查到过这个，但是不会用，
比如\small，放在reference.tex里第一行是无效的，放在\include{./references} 前面也无效。
但是，但是，但是，\small放在其他某章节.tex里或\include{}之前，\small就对该章节起了作用。

**Comment by NewFuture** [comment]
快一年没写过latex了，这些语法我也记不清了 😂

**Comment by jinjilr** [comment]
@NewFuture 
可以了，用这个\renewcommand*{\bibfont}{\small}
https://tex.stackexchange.com/questions/205432/with-biblatex-how-do-i-make-the-fontsize-of-the-bibliography-smaller
